[general]
import = [
  "~/.config/alacritty/themes/modus_vivendi.toml"
]

[env]
TERM = "alacritty"

[window]
opacity = 1
padding = { x = 8, y = 8 }
dynamic_padding = true

[font]
normal = { family = "Iosevka SS12", style = "Regular" }
bold = { family = "Iosevka SS12", style = "Bold" }
italic = { family = "Iosevka SS12", style = "Italic" }
size = 12.0

[cursor]
style = { shape = "Block", blinking = "On" }

[selection]
save_to_clipboard = true

[keyboard]
bindings = [
  { key = "V", mods = "Control|Shift", action = "Paste" },
  { key = "C", mods = "Control|Shift", action = "Copy" },
  { key = "Plus", mods = "Control", action = "IncreaseFontSize" },
  { key = "Minus", mods = "Control", action = "DecreaseFontSize" },
  { key = "Key0", mods = "Control", action = "ResetFontSize" },
]
