[colors.primary]
background = "#000000"
foreground = "#ffffff"
dim_foreground = "#989898"

[colors.cursor]
cursor = "#ffffff"
text = "#000000"

[colors.vi_mode_cursor]
cursor = "#fec43f"
text = "#000000"

[colors.selection]
background = "#5a5a5a"
text = "#ffffff"

[colors.search.matches]
background = "#2f447f"
foreground = "#ffffff"

[colors.search.focused_match]
background = "#2f7f9f"
foreground = "#ffffff"

[colors.hints.start]
background = "#fec43f"
foreground = "#000000"

[colors.hints.end]
background = "#d0bc00"
foreground = "#000000"

[colors.normal]
black   = "#1e1e1e"
red     = "#ff5f59"
green   = "#44bc44"
yellow  = "#d0bc00"
blue    = "#2fafff"
magenta = "#b6a0ff"
cyan    = "#00d3d0"
white   = "#989898"

[colors.bright]
black   = "#535353"
red     = "#ff6b55"
green   = "#44df44"
yellow  = "#fec43f"
blue    = "#79a8ff"
magenta = "#f78fe7"
cyan    = "#4ae2f0"
white   = "#ffffff"
